name: Build & Test .NET Deployment

on:
  push:
    branches: [main, user/** ]
  workflow_dispatch:
    inputs:
        reason:
          description: The reason for running the workflow
          required: false
          default: Manual run
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
    - name: Setup .NET
      uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815 # v3.4.2
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./AgentWithSPKnowledgeViaRetrieval.sln
    - name: Build
      run: dotnet build ./AgentWithSPKnowledgeViaRetrieval.sln -c Release
    - name: Test
      run: dotnet test ./AgentWithSPKnowledgeViaRetrieval.sln --verbosity normal -c Release
